pt-br docs updates

diff --git a/docs/pt-br/build b/docs/pt-br/build
--- a/docs/pt-br/build
+++ b/docs/pt-br/build
@@ -3,35 +3,90 @@ set +x
 set -e
 
 BASE_DIR=`cd "$(dirname "$0")"; pwd`
-pdf_generate=${pdf_generate:-true}
-use_fopub=${use_fopub:-false}
-fopub=${fopub:-~/Projects/github.com/asciidoctor/asciidoctor-fopub/bin/fopub}
+PROJECT_DIR=`cd "$BASE_DIR/../.."; pwd`
+RELATIVE_DIR=${BASE_DIR##$PROJECT_DIR/}
 
-cd "$BASE_DIR"
+config=build.conf
+[ -f "$BASE_DIR"/$config ] || config=$config.sample
+source "$BASE_DIR"/$config
 
-which asciidoctor > /dev/null || { echo "Install asciidoctor first!"; exit 1; }
+check_prerequisites() {
+  which asciidoctor > /dev/null || {
+    echo "ERROR: install asciidoctor first!"
+    exit 1
+  }
 
-clean() {
-  rm -f index.{html,xml}
-  rm -f blockchain-demo.pdf
-}
-
-main() {
-  asciidoctor index.adoc
-  result=$?
-
-  $pdf_generate || exit $result
-
-  if $use_fopub
+  if $generate_pdf
   then
-    asciidoctor -b docbook -d book -a data-uri! index.adoc
-    [ -x "$fopub" ] || { echo "WARN: $fopub not executable. PDF will not be generated!"; exit 0; }
-    $fopub index.xml
-  else
-    asciidoctor-pdf -o blockchain-demo.pdf index.adoc
+    if $use_fopub
+    then
+      [ -x "$fopub" ] || {
+        echo "ERROR: can't execute $fopub!"
+        exit 1
+      }
+    else
+      which asciidoctor-pdf > /dev/null || {
+        echo "ERROR: install asciidoctor-pdf first!"
+        exit 1
+      }
+    fi
   fi
 }
 
+clean() {
+  rm -f index.{html,xml}
+  rm -f $pdf_name $xml_name
+}
+
+build() {
+  local result
+
+  asciidoctor index.adoc
+  result=$?
+
+  $generate_pdf || exit $result
+
+  if $use_fopub
+  then
+    asciidoctor -b docbook -d book -a data-uri! index.adoc -o $xml_name
+    $fopub $xml_name
+  else
+    asciidoctor-pdf -o $pdf_name index.adoc
+  fi
+}
+
+publish() {
+  local published_dir=`mktemp -d`
+  local remote_repo=`git config --get remote.origin.url`
+  [ ".$remote_repo" = "." ] && {
+    echo 'The remote repository is not configured!'
+    return 1
+  }
+
+  mkdir -p "$published_dir/$RELATIVE_DIR"
+  rsync -av --delete \
+    --include='*.html' \
+    --include='*.pdf' \
+    --include='images/' \
+    --include='images/**' \
+    --exclude='*' \
+    . $published_dir/$RELATIVE_DIR/
+
+  local msg="Published at `date`"
+  cd "$published_dir"
+  git init
+  git add -A
+  git commit -m "$msg"
+  git push --force $remote_repo master:gh-pages
+  cd - &> /dev/null
+}
+
+check_prerequisites
+cd "$BASE_DIR"
 op=$1
-[ "$op" ] || op=main
-type $op &> /dev/null && $op || { echo "\"$op\" isn't an option!"; exit 1; }
+[ "$op" ] || op=build
+type $op &> /dev/null || {
+  echo "\"$op\" isn't an option!"
+  exit 1
+}
+$op
